export enum BlockedCause {
  BLOCK_BY_CHECK_AND_ASK = 'BLOCK_BY_CHECK_AND_ASK',
  BLOCK_BY_CONSENT = 'BLOCK_BY_CONSENT',
  BLOCK_BY_DNC = 'BLOCK_BY_DNC',
  BLOCK_BY_EXPIRED = 'BLOCK_BY_EXPIRED',
  BLOCK_BY_INVALID_PIN = 'BLOCK_BY_INVALID_PIN',
  COUNTRY_BLACK_LIST = 'COUNTRY_BLACK_LIST',
  CREDIT = 'CREDIT',
  DIRECT_PICKUP_FAIL = 'DIRECT_PICKUP_FAIL',
  DNC = 'DNC',
  FORWARD_LOOP = 'FORWARD_LOOP',
  GROUP_PICKUP_FAIL = 'GROUP_PICKUP_FAIL',
  NO_OUTBOUND_RULE = 'NO_OUTBOUND_RULE',
  UNKNOWN_ACTION = 'UNKNOWN_ACTION',
  USAGE_CONTROL = 'USAGE_CONTROL'
}
