export enum IncomingAction {
  RING_DEVICES = 'RING_DEVICES',
  RING_SIP_GATEWAY = 'RING_SIP_GATEWAY',
  RING_DEVICES_AND_SIP_GATEWAY = 'RING_DEVICES_AND_SIP_GATEWAY',
  CALL_FORWARDING = 'CALL_FORWARDING',
  NO_SET = 'NO_SET', // DND
  CALL_DELEGATION = 'CALL_DELEGATION'
}
